### ISSUE TITLE
Crash when used with shulker box tooltip

### ISSUE THREAD

**Issue by chimericdream** [MehradN/CaveSurvey#4]
One of my players discovered a client crash when he had a cave survey map in a shulker box. Whenever he hovered over the box, his client would crash with the stack trace below. This meant that he couldn't move the box from his inventory with the mouse. Fortunately, I was able to directly edit his player file to move the map from the shulker box to his inventory, but obviously this wasn't an ideal solution.

Here is the crash report he got:

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-06-01 23:56:43
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3222.method_37908()" because "player" is null
	at ir.mehradn.cavesurvey.item.CaveMapItem.getPolymerItemStack(CaveMapItem.java:204)
	at eu.pb4.polymer.core.impl.client.CoreClientUtils.getRenderingStack(CoreClientUtils.java:23)
	at net.minecraft.class_763.localvar$fca000$polymer-core$polymer$replaceItemStack(class_763.java:1017)
	at net.minecraft.class_763.method_3308(class_763.java)
	at net.minecraft.class_918.method_4019(class_918.java:250)
	at net.minecraft.class_332.method_51425(class_332.java:518)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.AbstractClientContainerItemTooltip.drawSlot(AbstractClientContainerItemTooltip.java:165)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.AbstractClientContainerItemTooltip.renderExpandedImage(AbstractClientContainerItemTooltip.java:79)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.ExpandableClientTooltipComponent.method_32666(ExpandableClientTooltipComponent.java:50)
	at net.minecraft.class_332.redirect$fle000$shulkerboxtooltip$drawPosAwareComponent(class_332.java:4279)
	at net.minecraft.class_332.method_51435(class_332.java:663)
	at net.minecraft.class_332.method_51437(class_332.java:601)
	at net.minecraft.class_465.shulkerboxtooltip$drawMouseoverTooltip(class_465.java:9717)
	at net.minecraft.class_465.shulkerboxtooltip$lockTooltipPosition(class_465.java:9300)
	at net.minecraft.class_465.redirect$flk000$shulkerboxtooltip$lockTooltipPosition(class_465.java:9711)
	at net.minecraft.class_465.method_2380(class_465.java:178)
	at net.minecraft.class_476.method_25394(class_476.java:29)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ir.mehradn.cavesurvey.item.CaveMapItem.getPolymerItemStack(CaveMapItem.java:204)
	at eu.pb4.polymer.core.impl.client.CoreClientUtils.getRenderingStack(CoreClientUtils.java:23)
	at net.minecraft.class_763.localvar$fca000$polymer-core$polymer$replaceItemStack(class_763.java:1017)
	at net.minecraft.class_763.method_3308(class_763.java)
	at net.minecraft.class_918.method_4019(class_918.java:250)
	at net.minecraft.class_332.method_51425(class_332.java:518)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.AbstractClientContainerItemTooltip.drawSlot(AbstractClientContainerItemTooltip.java:165)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.AbstractClientContainerItemTooltip.renderExpandedImage(AbstractClientContainerItemTooltip.java:79)
	at fuzs.puzzlesapi.api.client.iteminteractions.v1.tooltip.ExpandableClientTooltipComponent.method_32666(ExpandableClientTooltipComponent.java:50)
	at net.minecraft.class_332.redirect$fle000$shulkerboxtooltip$drawPosAwareComponent(class_332.java:4279)
	at net.minecraft.class_332.method_51435(class_332.java:663)
	at net.minecraft.class_332.method_51437(class_332.java:601)
	at net.minecraft.class_465.shulkerboxtooltip$drawMouseoverTooltip(class_465.java:9717)
	at net.minecraft.class_465.shulkerboxtooltip$lockTooltipPosition(class_465.java:9300)
	at net.minecraft.class_465.redirect$flk000$shulkerboxtooltip$lockTooltipPosition(class_465.java:9711)
	at net.minecraft.class_465.method_2380(class_465.java:178)
	at net.minecraft.class_476.method_25394(class_476.java:29)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_476
	Mouse location: Scaled: (229, 94). Absolute: (916.000000, 378.000000)
	Screen size: Scaled: (480, 253). Absolute: (1920, 1009). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['moshner'/108434, l='ClientLevel', x=537.02, y=125.00, z=-511.79]]
	Chunk stats: 1024, 313 F: 2767 L: 0 U: 55
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,104,48), Section: (at 0,8,0 in 1,6,3; chunk contains blocks 16,-64,48 to 31,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 604801020 game time, 615142878 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, world-of-pannotia.zip, wrench-rp.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 604208544 bytes (576 MiB) / 2071986176 bytes (1976 MiB) up to 7180648448 bytes (6848 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2111
	Graphics card #1 name: DisplayLink USB Device
	Graphics card #1 vendor: DisplayLink (0x17e9)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x4307
	Graphics card #1 versionInfo: DriverVersion=11.3.5139.0
	Graphics card #2 name: DisplayLink USB Device
	Graphics card #2 vendor: DisplayLink (0x17e9)
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: 0x4307
	Graphics card #2 versionInfo: DriverVersion=11.3.5139.0
	Graphics card #3 name: NVIDIA GeForce GTX 1650 with Max-Q Design
	Graphics card #3 vendor: NVIDIA (0x10de)
	Graphics card #3 VRAM (MB): 4095.00
	Graphics card #3 deviceId: 0x1f91
	Graphics card #3 versionInfo: DriverVersion=26.21.14.3091
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34663.01
	Virtual memory used (MB): 19227.48
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 63.34
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6848m -Xms256m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		advancementscreenshot: Advancement Screenshot 4.7
		allstackable: AllStackable v2.0.0-1.20.1
		alwaysloaded: Always Loaded Mod 1.1.1
		amecs: Amecs 1.3.10+mc.1.20.1
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
		anvilrestoration: Anvil Restoration 2.2
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.13
		areas: Areas 5.3
		armorpointspp: Armorpoints++ 3.1.2
			fiber: fiber 0.23.0-2
		ash_api: Ash API 3.0.2+1.20.1
		audioplayer: AudioPlayer 1.20.1-1.8.8
			admiral: Admiral 0.4.4+1.20.1
		authme: Auth Me 7.0.2+1.20
		auto_third_person: Auto Third Person 2.1
		autorun: AutoRun 0.5.0
		axolotlitemfix: Axolotl Item Fix 1.1.7
		balm-fabric: Balm 7.2.1
		better-trim-tooltips: Better Trim Tooltips 1.0.1
		betterbeacon: Better Beacons 1.1.0
			tf_ssf_sfort_ini_sf-ini: SF-INI 1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		bettermounthud: Better Mount HUD 1.2.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterspawnercontrol: Better Spawner Control 4.4
		betterstats: Better Statistics Screen 3.8.1+fabric-1.20.1
			tcdcommons: TCD Commons API 3.8.1+fabric-1.20.1
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthanmending: BetterThanMending 1.3.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		boatiview: Boat Item View Fabric 0.0.5
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bottled_allays: Bottled Allays 1.3.0
		bottledair: Bottled Air 2.3
		bottleyourxp: Bottle Your Xp 3.3
		bountiful: Bountiful 6.0.3+1.20.1
		bowinfinityfix: Bow Infinity Fix 2.6.0
		capes: Capes 1.5.2+1.20
		carpet: Carpet Mod 1.4.112+v230608
		cave-survey: Cave Survey 1.1.0
			cave-survey-client: Cave Survey Client 1.1.0
			ir_mehradn_common_: common 1.1.0
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		charmofundying: Charm of Undying 6.4.5+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		cherishedworlds: Cherished Worlds 6.1.5+1.20.1
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		clean_tooltips: Clean Tooltips 1.0
		cleancut: CleanCut 6.0
		cleanview: CleanView 1.20.1-v1-fabric
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.30
		completeconfig: CompleteConfig 2.5.0
			completeconfig-base: completeconfig-base 2.5.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.5.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.5.0
		compostables: Compostables 1.2.0
		conduitspreventdrowned: Conduits Prevent Drowned 3.6
		connectivity: Connectivity Mod 1.20.1-4.9
		continuity: Continuity 3.0.0-beta.4+1.20.1
		couplings: Couplings 1.9.5+1.20
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		crawl: Crawl 0.12.0
			mm: Manningham Mills 2.3
		cryingportals: Crying Portals 2.7
		cupboard: cupboard 1.20.1-2.3
		curvebuilding: CurveBuilding 0.5.0
			curvebuilding_curvebuilding-core_: curvebuilding-core unspecified
			org_yaml_snakeyaml: snakeyaml 1.29
		cyclepaintings: Cycle Paintings 3.5
		dailydad_server: Daily Dad (Server) 1.4.0
		deathbackup: Death Backup 3.2
		debugify: Debugify 1.20.1+2.0
		deepslatecutting: Deepslate Cutting 1.7.0
		deepslateinstamine: Deepslate Instamine 2.5_release
		diggusmaximus: Diggus Maximus 1.5.9-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		discontinuous_beacon_beams: Discontinuous Beacon Beams 1.1.9
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		dismountentity: Dismount Entity 3.2
		dispenser_configurator: Dispenser Configurator 1.2.10
		distractingtrims: DistractingTrims 2.0.3
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamic_fps: Dynamic FPS 3.4.0
		easyshulkerboxes: Easy Shulker Boxes 8.0.1
			puzzlesapi: Puzzles Api 8.1.4
				cardinal-components-base: Cardinal Components API (base) 5.2.2
				cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		elytraslot: Elytra Slot 6.3.0+1.20.1
		enchantedshulkers: Enchanted Shulkers 1.2.3
			io_hotmoka_toml4j: toml4j 0.7.3
			mixinsquared: MixinSquared 0.1.1
		enchantingcommands: Enchanting Commands 3.2
		enchantingtweaks: Enchanting Tweaks 1.2.1
			fabric-api-base: Fabric API Base 0.4.31+f4b7e424c0
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 1.2.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		extendedbonemeal: Extended Bone Meal 3.3
		extremesoundmuffler: Extreme sound muffler 3.41-fabric-1.20
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.18+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		fabrishot: Fabrishot 1.10.1
		fallingleaves: Falling Leaves 1.15.4
		faster_entity_animations: FastAnim 1.6
		fastpaintings: Fast Paintings 1.20-1.2.4
		firespreadtweaks: Fire Spread Tweaks 2.5
		fluidvoidfading: Fluid Void Fading 1.1.3
		followersteleporttoo: Followers Teleport Too 2.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.1-build.50
		fullbrightnesstoggle: Full Brightness Toggle 4.0
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
		grassseeds: Grass Seeds 3.2
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		guifollowers: GUI Followers 3.4
		handoveryouritems: Hand Over Your Items 3.2
		highlighter: Highlighter 1.1.9
		hoetweaks: Hoe Tweaks 3.4
		horsestatsvanilla: Horse Stats Vanilla 4.3.0
		iceberg: Iceberg 1.1.18
		icepreventscropgrowth: Ice Prevents Crop Growth 3.2
		identity: Identity 2.7.1-1.20.1
			omega-config: OmegaConfig 1.4.0+1.20.1
		indium: Indium 1.0.30+mc1.20.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		inventorytotem: Inventory Totem 3.2
		itemscroller: Item Scroller 0.20.0
		jade: Jade 11.8.0
		jamd: Just Another Mining Dimension 3.4.2+mc1.20.1
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		justplayerheads: Just Player Heads 3.3
		kambrik: Kambrik 6.1.1+1.20.1
		keepheadnames: Keep Head Names 1.5.1
		keepmysoiltilled: Keep My Soil Tilled 2.2
		kelpfertilizer: Kelp Fertilizer 3.2
		kiwi: Kiwi Library 11.5.4
		kleeslabs: KleeSlabs 15.0.0
		leaky: leaky Mod 1.20.1-1.6
		leaves_us_in_peace: Leaves Us In Peace 1.0.17
		libipn: libIPN 4.0.1
		libreexpfix: LibreExpFix 0.2.4b11-BETA
		lightoverlay: Light Overlay 8.0.0
		litematica: Litematica 0.15.3
		litematicatool: LitematicaTool 1.4.0
		lootr: Lootr 0.7.30.77
		malilib: MaLiLib 0.16.3
		maptooltip: Map Tooltip 3.0.0
		minecraft: Minecraft 1.20.1
		miniblockmerchants: Miniblock Merchants 2.1.1
		minihud: MiniHUD 0.27.0
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.9.17
		morebannerlayers: More Banner Layers 1.0.0-1.19
		nametagtweaks: Name Tag Tweaks 3.2
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		norecipebook: NoRecipeBook 2.4+1.20.1
		now-playing: Now Playing 1.4.3
		openpartiesandclaims: Open Parties and Claims 0.20.4
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		organizableplayscreens: Organizable Play Screens 1.1.5
		overworldpiglins: Overworld Piglins 1.4
		passablefoliage: Passable Foliage 1.20.1-fabric-8.2.1
		patchouli: Patchouli 1.20.1-84-FABRIC
		polymer-bundled: Polymer 0.5.19+1.20.1
			polymer-blocks: Polymer (Textured Blocks) 0.5.19+1.20.1
			polymer-common: Polymer (Common) 0.5.19+1.20.1
			polymer-core: Polymer (Core) 0.5.19+1.20.1
				polymer-networking: Polymer (Networking) 0.5.19+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.19+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.19+1.20.1
		preventdespawn: PreventDespawn 1.1
		puzzleslib: Puzzles Lib 8.1.17
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		rainbegoneritual: Rain Be Gone Ritual 3.2
		random_mob_sizes: Random Mob Sizes 1.20.1-1.3
		randombonemealflowers: Random Bone Meal Flowers 4.5
		reacharound: Reacharound 1.1.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replantingcrops: Replanting Crops 5.3
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 2.0.2
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.2
		seethroughlava: SeeThroughLava 4.0-1.20
		shuffle: Shuffle 9.0.0+1.20.1
		shulkerboxslot: Shulker Box Slot 5.1.1+1.20.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		silkspawners: SilkSpawners 1.1.3
		simplemagnets: Simple Magnets 1.1.10
		slimyfloor: Slimy Floor 1.20-1.2.8
		smallernetherportals: Smaller Nether Portals 3.6
		smoothchunk: Smooth chunk save Mod 1.20.1-3.5
		sneak_through_berries: Sneak Through Berries 8.0.0+1.20.1
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		softerhaybales: Softer Hay Bales 3.2
		sponj: Sponj 3.0.1
		starbidous_portal_linking: Corner Portal Linking 1.0.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		stendhal: Stendhal 1.4.1-1.20
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		superflatworldnoslimes: Superflat World No Slimes 3.2
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		suspiciouser: Suspiciouser 0.1.1
		taxfreelevels: Tax Free Levels 1.3.9
		timestamp_chat: Timestamp Chat 2.4.0+1.19.1
		trade_cycling: Trade Cycling 1.20.1-1.0.10
		trashslot: TrashSlot 15.1.0
		trenzalore: Trenzalore 3.3.10
			com_unrealdinnerbone_unrealconfig-core: UnRealConfig-core 12.3.4
			com_unrealdinnerbone_unrealconfig-gson: UnRealConfig-gson 12.3.4
		trinkets: Trinkets 3.7.1
		tweakeroo: Tweakeroo 0.17.1
		uglyscoreboardfix: Ugly Scoreboard Fix 2.10.0
		universal_shops: Universal Shops 1.3.2+1.20.1
			common-economy-api: Common Economy API 1.1.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			sgui: sgui 1.2.2+1.20
		vectorientation: Vectorientation 1.0.1a
		villagerdeathmessages: Villager Death Messages 3.3
		villagertweaks: Villager Tweaks 3.0.0
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.1-2.5.4
		wi_zoom: WI Zoom 1.5-MC1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		worldeditcui: WorldEditCUI 1.20+01
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroworldmap: Xaero's World Map 1.37.8
		yeetusexperimentus: Yeetus Experimentus 2.3.1-build.6+mc1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		youritemsaresafe: Your Items Are Safe 3.6
		yungsapi: YUNG's API 1.20-Fabric-4.0.3
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
		zombievillagersfromspawner: Zombie Villagers From Spawner 3.7
	Launched Version: fabric-loader-0.15.7-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 430.91, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: fabric
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

**Comment by MehradN** [comment]
Was he using one of those mods that show the content of a shulker box when hovered?

Can you try to see if a similar problem will happen when a vanilla map or a recovery compass is in a shulker box?

However, if you need the crash to be fixed as soon as possible, uninstalling the `cave-survey-1.1.0.jar` from the client's mod folder and installing `cave-survey-client-1.1.0.jar` instead, should fix the problem.
